// Listado de paises

export const paises = [
    { pais: "Afganistán", codigo: "AF" },
    { pais: "Albania", codigo: "AL" },
    { pais: "Alemania", codigo: "DE" },
    { pais: "Andorra", codigo: "AD" },
    { pais: "Angola", codigo: "AO" },
    { pais: "Antigua y Barbuda", codigo: "AG" },
    { pais: "Arabia Saudita", codigo: "SA" },
    { pais: "Argelia", codigo: "DZ" },
    { pais: "Argentina", codigo: "AR" },
    { pais: "Armenia", codigo: "AM" },
    { pais: "Australia", codigo: "AU" },
    { pais: "Austria", codigo: "AT" },
    { pais: "Azerbaiyán", codigo: "AZ" },
    { pais: "Bahamas", codigo: "BS" },
    { pais: "Bangladés", codigo: "BD" },
    { pais: "Barbados", codigo: "BB" },
    { pais: "Baréin", codigo: "BH" },
    { pais: "Bélgica", codigo: "BE" },
    { pais: "Belice", codigo: "BZ" },
    { pais: "Benín", codigo: "BJ" },
    { pais: "Bielorrusia", codigo: "BY" },
    { pais: "Birmania", codigo: "MM" },
    { pais: "Bolivia", codigo: "BO" },
    { pais: "Bosnia y Herzegovina", codigo: "BA" },
    { pais: "Botsuana", codigo: "BW" },
    { pais: "Brasil", codigo: "BR" },
    { pais: "Brunéi", codigo: "BN" },
    { pais: "Bulgaria", codigo: "BG" },
    { pais: "Burkina Faso", codigo: "BF" },
    { pais: "Burundi", codigo: "BI" },
    { pais: "Bután", codigo: "BT" },
    { pais: "Cabo Verde", codigo: "CV" },
    { pais: "Camboya", codigo: "KH" },
    { pais: "Camerún", codigo: "CM" },
    { pais: "Canadá", codigo: "CA" },
    { pais: "Catar", codigo: "QA" },
    { pais: "Chad", codigo: "TD" },
    { pais: "Chile", codigo: "CL" },
    { pais: "China", codigo: "CN" },
    { pais: "Chipre", codigo: "CY" },
    { pais: "Ciudad del Vaticano", codigo: "VA" },
    { pais: "Colombia", codigo: "CO" },
    { pais: "Comoras", codigo: "KM" },
    { pais: "Corea del Norte", codigo: "KP" },
    { pais: "Corea del Sur", codigo: "KR" },
    { pais: "Costa de Marfil", codigo: "CI" },
    { pais: "Costa Rica", codigo: "CR" },
    { pais: "Croacia", codigo: "HR" },
    { pais: "Cuba", codigo: "CU" },
    { pais: "Dinamarca", codigo: "DK" },
    { pais: "Dominica", codigo: "DM" },
    { pais: "Ecuador", codigo: "EC" },
    { pais: "Egipto", codigo: "EG" },
    { pais: "El Salvador", codigo: "SV" },
    { pais: "Emiratos Árabes Unidos", codigo: "AE" },
    { pais: "Eritrea", codigo: "ER" },
    { pais: "Eslovaquia", codigo: "SK" },
    { pais: "Eslovenia", codigo: "SI" },
    { pais: "España", codigo: "ES" },
    { pais: "Estados Unidos", codigo: "US" },
    { pais: "Estonia", codigo: "EE" },
    { pais: "Etiopía", codigo: "ET" },
    { pais: "Filipinas", codigo: "PH" },
    { pais: "Finlandia", codigo: "FI" },
    { pais: "Fiyi", codigo: "FJ" },
    { pais: "Francia", codigo: "FR" },
    { pais: "Gabón", codigo: "GA" },
    { pais: "Gambia", codigo: "GM" },
    { pais: "Georgia", codigo: "GE" },
    { pais: "Ghana", codigo: "GH" },
    { pais: "Granada", codigo: "GD" },
    { pais: "Grecia", codigo: "GR" },
    { pais: "Guatemala", codigo: "GT" },
    { pais: "Guinea", codigo: "GN" },
    { pais: "Guinea-Bisáu", codigo: "GW" },
    { pais: "Guinea Ecuatorial", codigo: "GQ" },
    { pais: "Guyana", codigo: "GY" },
    { pais: "Haití", codigo: "HT" },
    { pais: "Honduras", codigo: "HN" },
    { pais: "Hungría", codigo: "HU" },
    { pais: "India", codigo: "IN" },
    { pais: "Indonesia", codigo: "ID" },
    { pais: "Irak", codigo: "IQ" },
    { pais: "Irán", codigo: "IR" },
    { pais: "Irlanda", codigo: "IE" },
    { pais: "Islandia", codigo: "IS" },
    { pais: "Israel", codigo: "IL" },
    { pais: "Italia", codigo: "IT" },
    { pais: "Jamaica", codigo: "JM" },
    { pais: "Japón", codigo: "JP" },
    { pais: "Jordania", codigo: "JO" },
    { pais: "Kazajistán", codigo: "KZ" },
    { pais: "Kenia", codigo: "KE" },
    { pais: "Kirguistán", codigo: "KG" },
    { pais: "Kiribati", codigo: "KI" },
    { pais: "Kuwait", codigo: "KW" },
    { pais: "Laos", codigo: "LA" },
    { pais: "Lesoto", codigo: "LS" },
    { pais: "Letonia", codigo: "LV" },
    { pais: "Líbano", codigo: "LB" },
    { pais: "Liberia", codigo: "LR" },
    { pais: "Libia", codigo: "LY" },
    { pais: "Liechtenstein", codigo: "LI" },
    { pais: "Lituania", codigo: "LT" },
    { pais: "Luxemburgo", codigo: "LU" },
    { pais: "Madagascar", codigo: "MG" },
    { pais: "Malasia", codigo: "MY" },
    { pais: "Malawi", codigo: "MW" },
    { pais: "Maldivas", codigo: "MV" },
    { pais: "Malí", codigo: "ML" },
    { pais: "Malta", codigo: "MT" },
    { pais: "Marruecos", codigo: "MA" },
    { pais: "Mauricio", codigo: "MU" },
    { pais: "Mauritania", codigo: "MR" },
    { pais: "México", codigo: "MX" },
    { pais: "Micronesia", codigo: "FM" },
    { pais: "Moldavia", codigo: "MD" },
    { pais: "Mónaco", codigo: "MC" },
    { pais: "Mongolia", codigo: "MN" },
    { pais: "Montenegro", codigo: "ME" },
    { pais: "Mozambique", codigo: "MZ" },
    { pais: "Myanmar", codigo: "MM" },
    { pais: "Namibia", codigo: "NA" },
    { pais: "Nauru", codigo: "NR" },
    { pais: "Nepal", codigo: "NP" },
    { pais: "Nicaragua", codigo: "NI" },
    { pais: "Níger", codigo: "NE" },
    { pais: "Nigeria", codigo: "NG" },
    { pais: "Noruega", codigo: "NO" },
    { pais: "Nueva Zelanda", codigo: "NZ" },
    { pais: "Omán", codigo: "OM" },
    { pais: "Países Bajos", codigo: "NL" },
    { pais: "Pakistán", codigo: "PK" },
    { pais: "Palaos", codigo: "PW" },
    { pais: "Panamá", codigo: "PA" },
    { pais: "Papúa Nueva Guinea", codigo: "PG" },
    { pais: "Paraguay", codigo: "PY" },
    { pais: "Perú", codigo: "PE" },
    { pais: "Polonia", codigo: "PL" },
    { pais: "Portugal", codigo: "PT" },
    { pais: "Reino Unido", codigo: "GB" },
    { pais: "República Centroafricana", codigo: "CF" },
    { pais: "República Checa", codigo: "CZ" },
    { pais: "República del Congo", codigo: "CG" },
    { pais: "República Democrática del Congo", codigo: "CD" },
    { pais: "República Dominicana", codigo: "DO" },
    { pais: "República Sudafricana", codigo: "ZA" },
    { pais: "Ruanda", codigo: "RW" },
    { pais: "Rumanía", codigo: "RO" },
    { pais: "Rusia", codigo: "RU" },
    { pais: "Samoa", codigo: "WS" },
    { pais: "San Cristóbal y Nieves", codigo: "KN" },
    { pais: "San Marino", codigo: "SM" },
    { pais: "San Vicente y las Granadinas", codigo: "VC" },
    { pais: "Santa Lucía", codigo: "LC" },
    { pais: "Santo Tomé y Príncipe", codigo: "ST" },
    { pais: "Senegal", codigo: "SN" },
    { pais: "Serbia", codigo: "RS" },
    { pais: "Seychelles", codigo: "SC" },
    { pais: "Sierra Leona", codigo: "SL" },
    { pais: "Singapur", codigo: "SG" },
    { pais: "Siria", codigo: "SY" },
    { pais: "Somalia", codigo: "SO" },
    { pais: "Sri Lanka", codigo: "LK" },
    { pais: "Suazilandia", codigo: "SZ" },
    { pais: "Sudán", codigo: "SD" },
    { pais: "Sudán del Sur", codigo: "SS" },
    { pais: "Suecia", codigo: "SE" },
    { pais: "Suiza", codigo: "CH" },
    { pais: "Surinam", codigo: "SR" },
    { pais: "Tailandia", codigo: "TH" },
    { pais: "Tanzania", codigo: "TZ" },
    { pais: "Tayikistán", codigo: "TJ" },
    { pais: "Timor Oriental", codigo: "TL" },
    { pais: "Togo", codigo: "TG" },
    { pais: "Tonga", codigo: "TO" },
    { pais: "Trinidad y Tobago", codigo: "TT" },
    { pais: "Túnez", codigo: "TN" },
    { pais: "Turkmenistán", codigo: "TM" },
    { pais: "Turquía", codigo: "TR" },
    { pais: "Tuvalu", codigo: "TV" },
    { pais: "Ucrania", codigo: "UA" },
    { pais: "Uganda", codigo: "UG" },
    { pais: "Uruguay", codigo: "UY" },
    { pais: "Uzbekistán", codigo: "UZ" },
    { pais: "Vanuatu", codigo: "VU" },
    { pais: "Venezuela", codigo: "VE" },
    { pais: "Vietnam", codigo: "VN" },
    { pais: "Yemen", codigo: "YE" },
    { pais: "Yibuti", codigo: "DJ" },
    { pais: "Zambia", codigo: "ZM" },
    { pais: "Zimbabue", codigo: "ZW" },
];



